server:
  port: 8090
  tomcat.max-threads: 0
  tomcat.uri-encoding: UTF-8
 
spring:
  datasource:
    url : jdbc:mysql://10.237.3.81:3389/db_eolinker?useUnicode=true&amp;characterEncoding=utf8
    username : root
    password : 123456
    driverClassName : com.mysql.jdbc.Driver

mybatis:
  typeAliasesPackage: com.csc.test.platform.model 
  mapperLocations: classpath:mapper/*.xml

logging:
  config : classpath:logback-agent.xml